import fridgeGuardian.yr

from fridgeGuardian.yr import Yr
from pytest import fixture
from mock import patch, Mock
from dateutil.parser import parse

GREENWICH_LONGITUDE = -0.00143
GREENWICH_LATITUDE = 51.47782
YR_IDENTITY = "fridge-guardian github.com/iTom34/fridge-guardian"
WEATHER_FORCAST = {'geometry': {'coordinates': [-0.0014, 51.4778, 42], 'type': 'Point'},
 'properties': {'meta': {'units': {'air_pressure_at_sea_level': 'hPa',
                                   'air_temperature': 'celsius',
                                   'cloud_area_fraction': '%',
                                   'precipitation_amount': 'mm',
                                   'relative_humidity': '%',
                                   'wind_from_direction': 'degrees',
                                   'wind_speed': 'm/s'},
                         'updated_at': '2023-07-03T05:37:54Z'},
                'timeseries': [{'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.8,
                                                                 'air_temperature': 13.9,
                                                                 'cloud_area_fraction': 0.0,
                                                                 'relative_humidity': 75.3,
                                                                 'wind_from_direction': 251.0,
                                                                 'wind_speed': 5.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.0,
                                                                 'air_temperature': 15.2,
                                                                 'cloud_area_fraction': 0.0,
                                                                 'relative_humidity': 66.2,
                                                                 'wind_from_direction': 258.2,
                                                                 'wind_speed': 6.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T07:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.2,
                                                                 'air_temperature': 16.5,
                                                                 'cloud_area_fraction': 14.1,
                                                                 'relative_humidity': 56.5,
                                                                 'wind_from_direction': 259.0,
                                                                 'wind_speed': 6.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T08:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.0,
                                                                 'air_temperature': 17.6,
                                                                 'cloud_area_fraction': 25.0,
                                                                 'relative_humidity': 50.3,
                                                                 'wind_from_direction': 257.8,
                                                                 'wind_speed': 7.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-03T09:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.0,
                                                                 'air_temperature': 19.0,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 41.7,
                                                                 'wind_from_direction': 263.8,
                                                                 'wind_speed': 8.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.3},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T10:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.2,
                                                                 'air_temperature': 18.1,
                                                                 'cloud_area_fraction': 84.4,
                                                                 'relative_humidity': 51.7,
                                                                 'wind_from_direction': 249.8,
                                                                 'wind_speed': 8.1}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T11:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.9,
                                                                 'air_temperature': 18.7,
                                                                 'cloud_area_fraction': 63.3,
                                                                 'relative_humidity': 50.7,
                                                                 'wind_from_direction': 251.2,
                                                                 'wind_speed': 8.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.3,
                                                                 'air_temperature': 20.0,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 44.9,
                                                                 'wind_from_direction': 252.0,
                                                                 'wind_speed': 8.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T13:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.5,
                                                                 'air_temperature': 17.8,
                                                                 'cloud_area_fraction': 98.4,
                                                                 'relative_humidity': 56.2,
                                                                 'wind_from_direction': 249.7,
                                                                 'wind_speed': 8.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-03T14:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.9,
                                                                 'air_temperature': 18.3,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 56.5,
                                                                 'wind_from_direction': 242.2,
                                                                 'wind_speed': 9.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'lightrain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-03T15:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.5,
                                                                 'air_temperature': 18.8,
                                                                 'cloud_area_fraction': 50.0,
                                                                 'relative_humidity': 51.4,
                                                                 'wind_from_direction': 252.9,
                                                                 'wind_speed': 9.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-03T16:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.0,
                                                                 'air_temperature': 19.6,
                                                                 'cloud_area_fraction': 44.5,
                                                                 'relative_humidity': 47.2,
                                                                 'wind_from_direction': 257.1,
                                                                 'wind_speed': 9.1}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}}},
                                'time': '2023-07-03T17:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.1,
                                                                 'air_temperature': 19.0,
                                                                 'cloud_area_fraction': 29.7,
                                                                 'relative_humidity': 47.6,
                                                                 'wind_from_direction': 261.9,
                                                                 'wind_speed': 8.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_night'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-03T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.5,
                                                                 'air_temperature': 17.9,
                                                                 'cloud_area_fraction': 7.0,
                                                                 'relative_humidity': 49.7,
                                                                 'wind_from_direction': 260.7,
                                                                 'wind_speed': 7.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-03T19:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.4,
                                                                 'air_temperature': 16.6,
                                                                 'cloud_area_fraction': 3.9,
                                                                 'relative_humidity': 54.0,
                                                                 'wind_from_direction': 257.9,
                                                                 'wind_speed': 6.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-03T20:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.3,
                                                                 'air_temperature': 15.5,
                                                                 'cloud_area_fraction': 1.6,
                                                                 'relative_humidity': 58.0,
                                                                 'wind_from_direction': 252.3,
                                                                 'wind_speed': 6.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-03T21:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.7,
                                                                 'air_temperature': 14.6,
                                                                 'cloud_area_fraction': 10.2,
                                                                 'relative_humidity': 63.3,
                                                                 'wind_from_direction': 248.5,
                                                                 'wind_speed': 6.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}}},
                                'time': '2023-07-03T22:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.0,
                                                                 'air_temperature': 14.1,
                                                                 'cloud_area_fraction': 5.5,
                                                                 'relative_humidity': 66.2,
                                                                 'wind_from_direction': 248.3,
                                                                 'wind_speed': 5.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}}},
                                'time': '2023-07-03T23:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.0,
                                                                 'air_temperature': 13.5,
                                                                 'cloud_area_fraction': 21.1,
                                                                 'relative_humidity': 69.1,
                                                                 'wind_from_direction': 245.9,
                                                                 'wind_speed': 5.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}}},
                                'time': '2023-07-04T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.0,
                                                                 'air_temperature': 13.2,
                                                                 'cloud_area_fraction': 10.9,
                                                                 'relative_humidity': 70.9,
                                                                 'wind_from_direction': 243.3,
                                                                 'wind_speed': 4.9}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-04T01:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.9,
                                                                 'air_temperature': 12.9,
                                                                 'cloud_area_fraction': 5.5,
                                                                 'relative_humidity': 73.6,
                                                                 'wind_from_direction': 237.3,
                                                                 'wind_speed': 4.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-04T02:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.7,
                                                                 'air_temperature': 12.6,
                                                                 'cloud_area_fraction': 16.4,
                                                                 'relative_humidity': 77.3,
                                                                 'wind_from_direction': 232.2,
                                                                 'wind_speed': 4.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.7},
                                                          'summary': {'symbol_code': 'lightrainshowers_day'}}},
                                'time': '2023-07-04T03:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.6,
                                                                 'air_temperature': 12.3,
                                                                 'cloud_area_fraction': 87.5,
                                                                 'relative_humidity': 79.8,
                                                                 'wind_from_direction': 229.3,
                                                                 'wind_speed': 4.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 1.1},
                                                          'summary': {'symbol_code': 'rainshowers_day'}}},
                                'time': '2023-07-04T04:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.6,
                                                                 'air_temperature': 13.0,
                                                                 'cloud_area_fraction': 69.5,
                                                                 'relative_humidity': 77.9,
                                                                 'wind_from_direction': 227.8,
                                                                 'wind_speed': 4.4}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 1.3},
                                                          'summary': {'symbol_code': 'rainshowers_day'}}},
                                'time': '2023-07-04T05:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.4,
                                                                 'air_temperature': 14.2,
                                                                 'cloud_area_fraction': 12.5,
                                                                 'relative_humidity': 75.3,
                                                                 'wind_from_direction': 232.2,
                                                                 'wind_speed': 4.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rain'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 2.4},
                                                          'summary': {'symbol_code': 'rainshowers_day'}}},
                                'time': '2023-07-04T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.2,
                                                                 'air_temperature': 15.7,
                                                                 'cloud_area_fraction': 42.2,
                                                                 'relative_humidity': 71.8,
                                                                 'wind_from_direction': 238.7,
                                                                 'wind_speed': 4.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rain'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 3.0},
                                                          'summary': {'symbol_code': 'rain'}}},
                                'time': '2023-07-04T07:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.0,
                                                                 'air_temperature': 17.3,
                                                                 'cloud_area_fraction': 75.8,
                                                                 'relative_humidity': 68.0,
                                                                 'wind_from_direction': 228.9,
                                                                 'wind_speed': 5.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rain'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.7},
                                                          'summary': {'symbol_code': 'rainshowers_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 4.2},
                                                          'summary': {'symbol_code': 'rain'}}},
                                'time': '2023-07-04T08:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.9,
                                                                 'air_temperature': 15.9,
                                                                 'cloud_area_fraction': 97.7,
                                                                 'relative_humidity': 74.2,
                                                                 'wind_from_direction': 228.5,
                                                                 'wind_speed': 6.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.4},
                                                          'summary': {'symbol_code': 'rain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 3.6},
                                                          'summary': {'symbol_code': 'rain'}}},
                                'time': '2023-07-04T09:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.7,
                                                                 'air_temperature': 16.0,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 79.9,
                                                                 'wind_from_direction': 216.3,
                                                                 'wind_speed': 5.4}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'lightrain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 5.5},
                                                          'summary': {'symbol_code': 'heavyrain'}}},
                                'time': '2023-07-04T10:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.1,
                                                                 'air_temperature': 16.9,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 75.8,
                                                                 'wind_from_direction': 221.5,
                                                                 'wind_speed': 5.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 1.1},
                                                          'summary': {'symbol_code': 'heavyrain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 5.7},
                                                          'summary': {'symbol_code': 'heavyrain'}}},
                                'time': '2023-07-04T11:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.6,
                                                                 'air_temperature': 15.9,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 86.0,
                                                                 'wind_from_direction': 211.6,
                                                                 'wind_speed': 6.4}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.5},
                                                          'summary': {'symbol_code': 'rain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 4.6},
                                                          'summary': {'symbol_code': 'rain'}}},
                                'time': '2023-07-04T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.1,
                                                                 'air_temperature': 17.7,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 74.6,
                                                                 'wind_from_direction': 218.3,
                                                                 'wind_speed': 7.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 1.2},
                                                          'summary': {'symbol_code': 'heavyrain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 4.1},
                                                          'summary': {'symbol_code': 'rain'}}},
                                'time': '2023-07-04T13:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1008.7,
                                                                 'air_temperature': 17.4,
                                                                 'cloud_area_fraction': 99.2,
                                                                 'relative_humidity': 79.5,
                                                                 'wind_from_direction': 233.7,
                                                                 'wind_speed': 6.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'lightrain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 2.9},
                                                          'summary': {'symbol_code': 'rainshowers_day'}}},
                                'time': '2023-07-04T14:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1007.7,
                                                                 'air_temperature': 19.1,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 64.9,
                                                                 'wind_from_direction': 243.7,
                                                                 'wind_speed': 7.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 2.3},
                                                          'summary': {'symbol_code': 'heavyrain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 2.8},
                                                          'summary': {'symbol_code': 'rainshowers_day'}}},
                                'time': '2023-07-04T15:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1007.9,
                                                                 'air_temperature': 16.1,
                                                                 'cloud_area_fraction': 99.2,
                                                                 'relative_humidity': 80.2,
                                                                 'wind_from_direction': 245.5,
                                                                 'wind_speed': 6.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.4},
                                                          'summary': {'symbol_code': 'rain'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.5},
                                                          'summary': {'symbol_code': 'lightrainshowers_day'}}},
                                'time': '2023-07-04T16:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1007.4,
                                                                 'air_temperature': 16.0,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 82.3,
                                                                 'wind_from_direction': 229.3,
                                                                 'wind_speed': 4.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-04T17:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1007.4,
                                                                 'air_temperature': 16.3,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 82.7,
                                                                 'wind_from_direction': 238.2,
                                                                 'wind_speed': 4.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-04T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1007.7,
                                                                 'air_temperature': 16.2,
                                                                 'cloud_area_fraction': 34.4,
                                                                 'relative_humidity': 76.5,
                                                                 'wind_from_direction': 254.6,
                                                                 'wind_speed': 4.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-04T19:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1008.2,
                                                                 'air_temperature': 14.9,
                                                                 'cloud_area_fraction': 8.6,
                                                                 'relative_humidity': 75.5,
                                                                 'wind_from_direction': 265.4,
                                                                 'wind_speed': 3.9}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-04T20:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.0,
                                                                 'air_temperature': 13.4,
                                                                 'cloud_area_fraction': 10.2,
                                                                 'relative_humidity': 79.8,
                                                                 'wind_from_direction': 246.5,
                                                                 'wind_speed': 3.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-04T21:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.4,
                                                                 'air_temperature': 13.0,
                                                                 'cloud_area_fraction': 11.7,
                                                                 'relative_humidity': 76.4,
                                                                 'wind_from_direction': 240.9,
                                                                 'wind_speed': 4.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-04T22:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.7,
                                                                 'air_temperature': 12.6,
                                                                 'cloud_area_fraction': 6.2,
                                                                 'relative_humidity': 75.9,
                                                                 'wind_from_direction': 244.8,
                                                                 'wind_speed': 4.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-04T23:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.9,
                                                                 'air_temperature': 12.2,
                                                                 'cloud_area_fraction': 3.1,
                                                                 'relative_humidity': 80.3,
                                                                 'wind_from_direction': 245.7,
                                                                 'wind_speed': 4.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-05T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1009.9,
                                                                 'air_temperature': 11.8,
                                                                 'cloud_area_fraction': 6.2,
                                                                 'relative_humidity': 82.3,
                                                                 'wind_from_direction': 245.5,
                                                                 'wind_speed': 4.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T01:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.1,
                                                                 'air_temperature': 11.5,
                                                                 'cloud_area_fraction': 0.0,
                                                                 'relative_humidity': 81.9,
                                                                 'wind_from_direction': 241.3,
                                                                 'wind_speed': 4.4}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T02:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.2,
                                                                 'air_temperature': 11.2,
                                                                 'cloud_area_fraction': 0.8,
                                                                 'relative_humidity': 83.3,
                                                                 'wind_from_direction': 238.0,
                                                                 'wind_speed': 4.3}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T03:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.5,
                                                                 'air_temperature': 10.9,
                                                                 'cloud_area_fraction': 3.9,
                                                                 'relative_humidity': 85.9,
                                                                 'wind_from_direction': 238.8,
                                                                 'wind_speed': 4.3}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T04:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1010.9,
                                                                 'air_temperature': 11.7,
                                                                 'cloud_area_fraction': 2.3,
                                                                 'relative_humidity': 85.0,
                                                                 'wind_from_direction': 240.3,
                                                                 'wind_speed': 4.3}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T05:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.3,
                                                                 'air_temperature': 13.3,
                                                                 'cloud_area_fraction': 18.7,
                                                                 'relative_humidity': 80.7,
                                                                 'wind_from_direction': 253.0,
                                                                 'wind_speed': 4.9}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.7,
                                                                 'air_temperature': 14.8,
                                                                 'cloud_area_fraction': 60.2,
                                                                 'relative_humidity': 76.9,
                                                                 'wind_from_direction': 265.0,
                                                                 'wind_speed': 5.4}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T07:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.1,
                                                                 'air_temperature': 16.2,
                                                                 'cloud_area_fraction': 89.8,
                                                                 'relative_humidity': 69.0,
                                                                 'wind_from_direction': 268.5,
                                                                 'wind_speed': 5.1}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T08:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.4,
                                                                 'air_temperature': 17.5,
                                                                 'cloud_area_fraction': 17.2,
                                                                 'relative_humidity': 63.8,
                                                                 'wind_from_direction': 260.3,
                                                                 'wind_speed': 4.4}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T09:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.7,
                                                                 'air_temperature': 18.7,
                                                                 'cloud_area_fraction': 46.9,
                                                                 'relative_humidity': 59.8,
                                                                 'wind_from_direction': 262.0,
                                                                 'wind_speed': 4.7}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T10:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.7,
                                                                 'air_temperature': 19.4,
                                                                 'cloud_area_fraction': 99.2,
                                                                 'relative_humidity': 55.9,
                                                                 'wind_from_direction': 257.6,
                                                                 'wind_speed': 5.2}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T11:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.5,
                                                                 'air_temperature': 19.9,
                                                                 'cloud_area_fraction': 90.6,
                                                                 'relative_humidity': 49.9,
                                                                 'wind_from_direction': 256.6,
                                                                 'wind_speed': 5.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.5,
                                                                 'air_temperature': 19.7,
                                                                 'cloud_area_fraction': 26.6,
                                                                 'relative_humidity': 49.1,
                                                                 'wind_from_direction': 250.9,
                                                                 'wind_speed': 6.0}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T13:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.4,
                                                                 'air_temperature': 21.0,
                                                                 'cloud_area_fraction': 21.1,
                                                                 'relative_humidity': 42.1,
                                                                 'wind_from_direction': 255.6,
                                                                 'wind_speed': 6.5}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T14:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.5,
                                                                 'air_temperature': 20.8,
                                                                 'cloud_area_fraction': 18.7,
                                                                 'relative_humidity': 42.1,
                                                                 'wind_from_direction': 265.2,
                                                                 'wind_speed': 6.8}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T15:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.6,
                                                                 'air_temperature': 20.8,
                                                                 'cloud_area_fraction': 27.3,
                                                                 'relative_humidity': 40.2,
                                                                 'wind_from_direction': 264.6,
                                                                 'wind_speed': 6.7}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-05T16:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.6,
                                                                 'air_temperature': 20.5,
                                                                 'cloud_area_fraction': 51.6,
                                                                 'relative_humidity': 40.7,
                                                                 'wind_from_direction': 261.1,
                                                                 'wind_speed': 6.8}},
                                         'next_1_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-05T17:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.8,
                                                                 'air_temperature': 19.8,
                                                                 'cloud_area_fraction': 70.3,
                                                                 'relative_humidity': 43.6,
                                                                 'wind_from_direction': 255.5,
                                                                 'wind_speed': 6.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_night'}}},
                                'time': '2023-07-05T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1014.6,
                                                                 'air_temperature': 13.8,
                                                                 'cloud_area_fraction': 10.9,
                                                                 'relative_humidity': 76.7,
                                                                 'wind_from_direction': 244.0,
                                                                 'wind_speed': 3.3}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-06T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.2,
                                                                 'air_temperature': 13.4,
                                                                 'cloud_area_fraction': 3.1,
                                                                 'relative_humidity': 82.2,
                                                                 'wind_from_direction': 234.9,
                                                                 'wind_speed': 3.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}}},
                                'time': '2023-07-06T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.8,
                                                                 'air_temperature': 20.6,
                                                                 'cloud_area_fraction': 98.4,
                                                                 'relative_humidity': 45.5,
                                                                 'wind_from_direction': 235.3,
                                                                 'wind_speed': 5.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-06T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.6,
                                                                 'air_temperature': 19.5,
                                                                 'cloud_area_fraction': 22.7,
                                                                 'relative_humidity': 52.9,
                                                                 'wind_from_direction': 216.1,
                                                                 'wind_speed': 5.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}}},
                                'time': '2023-07-06T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1017.7,
                                                                 'air_temperature': 13.7,
                                                                 'cloud_area_fraction': 88.3,
                                                                 'relative_humidity': 83.2,
                                                                 'wind_from_direction': 190.5,
                                                                 'wind_speed': 3.3}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-07T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1017.5,
                                                                 'air_temperature': 15.0,
                                                                 'cloud_area_fraction': 0.0,
                                                                 'relative_humidity': 84.7,
                                                                 'wind_from_direction': 102.6,
                                                                 'wind_speed': 0.9}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}}},
                                'time': '2023-07-07T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1017.2,
                                                                 'air_temperature': 24.3,
                                                                 'cloud_area_fraction': 3.1,
                                                                 'relative_humidity': 42.6,
                                                                 'wind_from_direction': 189.9,
                                                                 'wind_speed': 5.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}}},
                                'time': '2023-07-07T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.9,
                                                                 'air_temperature': 23.9,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 45.0,
                                                                 'wind_from_direction': 173.0,
                                                                 'wind_speed': 3.4}},
                                         'next_12_hours': {'summary': {'symbol_code': 'cloudy'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-07T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.7,
                                                                 'air_temperature': 16.1,
                                                                 'cloud_area_fraction': 93.7,
                                                                 'relative_humidity': 85.1,
                                                                 'wind_from_direction': 33.0,
                                                                 'wind_speed': 1.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-08T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1013.9,
                                                                 'air_temperature': 20.2,
                                                                 'cloud_area_fraction': 90.6,
                                                                 'relative_humidity': 63.8,
                                                                 'wind_from_direction': 117.1,
                                                                 'wind_speed': 4.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-08T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1013.6,
                                                                 'air_temperature': 28.3,
                                                                 'cloud_area_fraction': 59.4,
                                                                 'relative_humidity': 48.6,
                                                                 'wind_from_direction': 151.8,
                                                                 'wind_speed': 4.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-08T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1013.8,
                                                                 'air_temperature': 27.1,
                                                                 'cloud_area_fraction': 82.0,
                                                                 'relative_humidity': 56.0,
                                                                 'wind_from_direction': 184.2,
                                                                 'wind_speed': 3.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_night'}}},
                                'time': '2023-07-08T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1014.8,
                                                                 'air_temperature': 20.1,
                                                                 'cloud_area_fraction': 16.4,
                                                                 'relative_humidity': 87.2,
                                                                 'wind_from_direction': 159.5,
                                                                 'wind_speed': 1.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}}},
                                'time': '2023-07-09T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.6,
                                                                 'air_temperature': 21.2,
                                                                 'cloud_area_fraction': 93.7,
                                                                 'relative_humidity': 83.8,
                                                                 'wind_from_direction': 218.3,
                                                                 'wind_speed': 2.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-09T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1017.2,
                                                                 'air_temperature': 27.3,
                                                                 'cloud_area_fraction': 19.5,
                                                                 'relative_humidity': 51.6,
                                                                 'wind_from_direction': 229.3,
                                                                 'wind_speed': 3.9}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_day'}}},
                                'time': '2023-07-09T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1017.2,
                                                                 'air_temperature': 25.6,
                                                                 'cloud_area_fraction': 10.2,
                                                                 'relative_humidity': 52.1,
                                                                 'wind_from_direction': 210.6,
                                                                 'wind_speed': 3.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-09T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1018.4,
                                                                 'air_temperature': 19.0,
                                                                 'cloud_area_fraction': 53.9,
                                                                 'relative_humidity': 71.6,
                                                                 'wind_from_direction': 261.3,
                                                                 'wind_speed': 2.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'fair_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_night'}}},
                                'time': '2023-07-10T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1017.0,
                                                                 'air_temperature': 18.2,
                                                                 'cloud_area_fraction': 8.6,
                                                                 'relative_humidity': 77.9,
                                                                 'wind_from_direction': 279.7,
                                                                 'wind_speed': 1.5}},
                                         'next_12_hours': {'summary': {'symbol_code': 'rainshowers_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_day'}}},
                                'time': '2023-07-10T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1013.3,
                                                                 'air_temperature': 26.4,
                                                                 'cloud_area_fraction': 77.3,
                                                                 'relative_humidity': 48.9,
                                                                 'wind_from_direction': 96.3,
                                                                 'wind_speed': 2.2}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 14.4},
                                                          'summary': {'symbol_code': 'heavyrainshowers_day'}}},
                                'time': '2023-07-10T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1011.3,
                                                                 'air_temperature': 19.9,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 79.3,
                                                                 'wind_from_direction': 295.1,
                                                                 'wind_speed': 3.1}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.1},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-10T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1013.1,
                                                                 'air_temperature': 16.1,
                                                                 'cloud_area_fraction': 7.8,
                                                                 'relative_humidity': 83.4,
                                                                 'wind_from_direction': 212.4,
                                                                 'wind_speed': 5.7}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'clearsky_night'}}},
                                'time': '2023-07-11T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1014.7,
                                                                 'air_temperature': 16.4,
                                                                 'cloud_area_fraction': 46.1,
                                                                 'relative_humidity': 77.7,
                                                                 'wind_from_direction': 217.9,
                                                                 'wind_speed': 5.8}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.5},
                                                          'summary': {'symbol_code': 'partlycloudy_day'}}},
                                'time': '2023-07-11T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.3,
                                                                 'air_temperature': 21.6,
                                                                 'cloud_area_fraction': 96.1,
                                                                 'relative_humidity': 54.0,
                                                                 'wind_from_direction': 228.2,
                                                                 'wind_speed': 9.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.2},
                                                          'summary': {'symbol_code': 'cloudy'}}},
                                'time': '2023-07-11T12:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.4,
                                                                 'air_temperature': 20.0,
                                                                 'cloud_area_fraction': 36.7,
                                                                 'relative_humidity': 61.2,
                                                                 'wind_from_direction': 221.6,
                                                                 'wind_speed': 6.6}},
                                         'next_12_hours': {'summary': {'symbol_code': 'partlycloudy_night'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'fair_night'}}},
                                'time': '2023-07-11T18:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1015.8,
                                                                 'air_temperature': 15.4,
                                                                 'cloud_area_fraction': 43.7,
                                                                 'relative_humidity': 88.4,
                                                                 'wind_from_direction': 203.4,
                                                                 'wind_speed': 4.0}},
                                         'next_12_hours': {'summary': {'symbol_code': 'lightrainshowers_day'}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.0},
                                                          'summary': {'symbol_code': 'partlycloudy_night'}}},
                                'time': '2023-07-12T00:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.6,
                                                                 'air_temperature': 17.5,
                                                                 'cloud_area_fraction': 100.0,
                                                                 'relative_humidity': 79.2,
                                                                 'wind_from_direction': 190.9,
                                                                 'wind_speed': 5.7}},
                                         'next_6_hours': {'details': {'precipitation_amount': 0.6},
                                                          'summary': {'symbol_code': 'lightrain'}}},
                                'time': '2023-07-12T06:00:00Z'},
                               {'data': {'instant': {'details': {'air_pressure_at_sea_level': 1012.3,
                                                                 'air_temperature': 22.2,
                                                                 'cloud_area_fraction': 25.8,
                                                                 'relative_humidity': 48.8,
                                                                 'wind_from_direction': 234.0,
                                                                 'wind_speed': 7.3}}},
                                'time': '2023-07-12T12:00:00Z'}]},
 'type': 'Feature'}
HEADERS = {'Expires': 'Mon, 03 Jul 2023 07:25:03 GMT'}

@fixture
def greenwich_weather():
    greenwich_weather = Yr(GREENWICH_LONGITUDE, GREENWICH_LATITUDE, YR_IDENTITY)
    return greenwich_weather


def test_constructor(greenwich_weather):
    assert greenwich_weather.longitude == GREENWICH_LONGITUDE
    assert greenwich_weather.latitude == GREENWICH_LATITUDE
    assert greenwich_weather.identity == YR_IDENTITY


def test_build_url(greenwich_weather):
    assert greenwich_weather._build_url() == \
           f"https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=51.4778&lon=-0.0014"


@patch('fridgeGuardian.yr.datetime.now', name='mock_now')
def test_get_weather_forcast(mock_now, greenwich_weather):

    # First request
    mock_now.return_value = parse
    mock_response = Mock(name='mock_response')
    mock_response.status_code = 200
    mock_response.headers = HEADERS
    mock_response.json = WEATHER_FORCAST

    assert greenwich_weather.get_weather_forcast() == WEATHER_FORCAST
    assert greenwich_weather.expire_raw == HEADERS['Expires']
    assert greenwich_weather.expire == parse(HEADERS['Expires'])

    assert greenwich_weather.get_weather_forcast() == WEATHER_FORCAST

    Weather

@patch('fridgeGuardian.yr.requests.get', name='mock_get')
def test_request(mock_get, greenwich_weather):
    url = "test_URL"

    # if_modified_since = False
    greenwich_weather._build_url = Mock(name='mock_build_url', return_value=url)
    mock_get.return_value = "mocked_response"

    assert greenwich_weather._request(if_modified_since=False) == "mocked_response"
    assert mock_get.assert_called_with(url, {'user-agent': greenwich_weather.identity})

